apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nocode-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/nocode-platform'
    targetRevision: main
    path: kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
