name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: your-dockerhub/frontend:latest

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: your-dockerhub/backend:latest

    - name: Trigger ArgoCD Sync
      run: |
        curl -X POST https://argocd.your-domain.com/api/v1/applications/nocode-platform/sync \
          -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN"
